services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./docker-volumes/data:/data/db

  mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=freelancer
      - MYSQL_DATABASE=freelancer_auth
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
    ports:
      - '3306:3306'
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=freelancer
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=freelancer_review
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4.0.4-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=freelancer
      - RABBITMQ_DEFAULT_PASS=freelancerpass
    ports:
      - '5672:5672'
      - '15672:15672'

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: "true"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true"
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./volumes/docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.17.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elastic:admin1234@elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elastic:admin1234@elasticsearch_container:9200"]
    ports:
      - '5601:5601'
    networks:
      - elastic
    volumes:
      - ./volumes/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  apmServer:
    image: docker.elastic.co/apm/apm-server:8.17.0
    container_name: apm_server_container
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana_container:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana_container:5601
        -E apm-server.kibana.protocol=http
        -E strict.perms=false
        -E apm-server.auth.anonymous.enabled=true

  metricbeat:
    container_name: metricbeat_container
    image: docker.elastic.co/beats/metricbeat:8.17.0
    restart: always
    user: root
    ports:
      - '5066:5066'
    networks:
      - elastic
    volumes:
      - ./volumes/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch

  heartbeat:
    container_name: heartbeat_container
    image: docker.elastic.co/beats/heartbeat:8.17.0
    restart: always
    user: root
    hostname: heartbeat
    cap_add:
      - NET_RAW
    networks:
      - elastic
    volumes:
      - ./volumes/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
  
  gateway:
    container_name: gateway_container
    build:
      context: ../server/1-apiGateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '4000:4000'
    env_file: ../server/1-apiGateway/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - SECRET_KEY_ONE=032c5c3cfc37938ae6dd43d3a3ec7834
      - SECRET_KEY_TWO=d66e377018c0bc0b5772bbc9b131e6d9
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq

  notifications:
    container_name: notification_container
    build:
      context: ../server/2-notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '4001:4001'
    env_file: ../server/2-notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - SENDER_EMAIL=
      - SENDER_EMAIL_PASSWORD=
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq

  users:
    container_name: users_container
    build:
      context: ../server/4-users-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '4003:4003'
    env_file: ../server/2-notification-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/freelancer-users
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - CLOUD_NAME=ddplizmv9
      - CLOUD_API_KEY=815524726748453
      - CLOUD_API_SECRET=UPhQrWYUxdUwjD_OI_eSAz76Z48
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
      - rabbitmq

  gig:
    container_name: gig_container
    build:
      context: ../server/5-gig-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4004:4004
    env_file: ../server/5-gig-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://127.0.0.1:27017/freelancer-gig
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://localhost:4000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@localhost:5672
      - CLOUD_NAME=ddplizmv9
      - CLOUD_API_KEY=815524726748453
      - CLOUD_API_SECRET=UPhQrWYUxdUwjD_OI_eSAz76Z48
      - REDIS_HOST=redis://localhost:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@localhost:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb

  chat:
    container_name: chat_container
    build:
      context: ../server/6-chat-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4005:4005
    env_file: ../server/6-chat-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://127.0.0.1:27017/freelancer-chat
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://localhost:4000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@localhost:5672
      - CLOUD_NAME=ddplizmv9
      - CLOUD_API_KEY=
      - CLOUD_API_SECRET=
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@localhost:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    
  order:
    container_name: order_container
    build:
      context: ../server/7-order-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4006:4006
    env_file: ../server/7-order-service/.env
    environment: 
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://127.0.0.1:27017/freelancer-chat
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - CLIENT_URL=
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://localhost:4000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@localhost:5672
      - CLOUD_NAME=ddplizmv9
      - CLOUD_API_KEY=815524726748453
      - CLOUD_API_SECRET=UPhQrWYUxdUwjD_OI_eSAz76Z48
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@localhost:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
      - STRIPE_PUBLIC_KEY=
      - STRIPE_API_KEY=
    depends_on:
      - elasticsearch
      - mongodb
    

  review:
    container_name: order_container
    build:
      context: ../server/8-review-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4007:4007
    env_file: ../server/8-review-service/.env 
    environment:
      - ENABLE_APM=0
      - DATABASE_HOST=localhost
      - DATABASE_USER=freelancer
      - DATABASE_PASSWORD=api
      - DATABASE_NAME=freelancer_review
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - CLIENT_URL=
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - AP_GATEWAY_URL=http://localhost:4000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@localhost:5672
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@localhost:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=


networks:
  elastic:
    name: elastic