name: Publish
on:
    push:
        branches: [master]
    pull_request: 
        branches: [master]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '22.x'
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - run: |
                  echo @harish-x:npm.pkg.github.com/ > build/.npmrc
                  echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
            - run: npm publish
              working-directory: ./build
              env:
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
