apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: production
spec:
  storageClassName: elasticsearch-local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: production
spec:
  storageClassName: elasticsearch-local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce